spring.application.name=SmartTaskAI

# Gemini AI API
gemini.api.key=

# JWT Secret
jwt.secret=

# Konfigurasi Koneksi MySQL
spring.datasource.url=jdbc:mysql://
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Meminta Spring membuatkan tabel otomatis berdasarkan file Task.kt
spring.jpa.hibernate.ddl-auto=update

# (Opsional) Menampilkan query SQL di terminal agar mudah dicek
spring.jpa.show-sql=true

spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.keepalive-time=30000