spring.application.name=SmartTaskAI

# Gemini AI API
gemini.api.key=AIzaSyCD7WuX1qihrSK06kVKmNd4c3PgrdahX3A

# JWT Secret
jwt.secret=IniAdalahKunciRahasiaSmartTaskAplikasiICTSupportSangatPanjangSekali

# Konfigurasi Koneksi MySQL
spring.datasource.url=jdbc:mysql://103.154.145.125:3306/smarttaskai_db
spring.datasource.username=vince
spring.datasource.password=NugasALPVisProg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Meminta Spring membuatkan tabel otomatis berdasarkan file Task.kt
spring.jpa.hibernate.ddl-auto=update

# (Opsional) Menampilkan query SQL di terminal agar mudah dicek
spring.jpa.show-sql=true

spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.keepalive-time=30000